### ISSUE TITLE
Document usage of Settings_ShowProcessCommandLine

### ISSUE THREAD

**Issue by gep13** [cake-build/website#1234] opened 2020-11-20 09:02 UTC
I thought we had an issue for this, but I looked and I couldn't see one.

**Comment by pascalberger** [comment] 2020-11-20 14:55
Closing as a duplicate of #907

**Closed by pascalberger** 2020-11-20 14:55 UTC
Labels: documentation

**Comment by gep13** [comment] 2020-11-20 14:59
That is bizarre!  I searched, but I couldn't find that issue!  Apologies!

**Comment by pascalberger** [comment] 2020-11-20 15:00
> That is bizarre! I searched, but I couldn't find that issue! Apologies!

It didn't include `Settings_ShowProcessCommandLine` anywhere :) Updated title now.

**Comment by gep13** [comment] 2020-11-20 15:15
Ah, now the world makes sense again (well, a little bit more sense anyway!)
