### ISSUE TITLE
Do we still need YAML files for addins documentation?

### ISSUE THREAD

**Issue by Jericho** [cake-build/website#700] opened 2019-08-24 14:00 UTC
It seems to me there is some duplication of effort between the AddinDiscoverer and the process that generates documentation for addins. Also, there's human intervention required to merge the PRs generated by AddinDiscoverer and I'm wondering if this could be avoided if the documentation process was improved to discover the addins on nuget and read the metadata for each nuget package.

Currently the process looks something like this:
- AddinDisco searches NuGet.org to discover all existing addins
- AddinDisco downloads all discovered packages
- AddinDisco reads nuspec in each package and generates YAML files
- AddinDisco compares the generated yaml files with the existing yaml files in the website repo
- AddinDisco raises issues+PRs to add/update/delete yaml files
- Cake team member reviews and merges PRs
- Documentation process reads yaml files
- Documentation process downloads all packages
- Documentation process reads DLLs in packages and generates documentation

As you can see, packages are downloaded twice and manual intervention is necessary to review and approve PRs. I'm thinking that this process could be simplified if we abandoned the YAML files synchronization and the Documentation process searched NuGet.org to discover existing addins.

What I think would be a better and simpler process would be something like this:
- Documentation process searches NuGet.org to discover all existing addins
- Documentation process downloads all discovered packages
- Documentation process reads nuspec and DLLs in each package and generates documentation

/cc @daveaglick @devlead @gep13

**Comment by daveaglick** [comment] 2019-08-26 12:13
+1000 to this. I'll be totally rebuilding the website later this year or early next (depending on when Statiq actually ships). That'll be the time to merge the code from AddinDiscoverer into the Statiq site build - and working better with real customization code happens to be one of the driving motivations behind Statiq so it should be a good fit.

I guess the real question is if the addin discoverer covers all cases or if we'll still need the YAML files to supplement. Are there addins that the discoverer doesn't pick up on?

**Comment by gep13** [comment] 2019-08-26 12:25
@daveaglick Cake.AddinDiscoverer finds addins published to NuGet.org by looking for packages published using the `Cake.*` prefix.  To the best of my knowledge, that means it has found 99.64% of the addins that I know to be out there.  The only one that I know about that it doesn't currently find is the MagicChunks addin, which is published simply using the MagicChunks id on NuGet.org.  So having the ability to still supplement the list would be a good idea.

**Comment by daveaglick** [comment] 2019-08-26 12:27
Interesting - we might still be able to eliminate the full YAML files then and just provide a set of supplementary package IDs for packages that don't start with `Cake.*`

**Comment by gep13** [comment] 2019-08-26 12:29
I haven't looked at the code, but perhaps @Jericho can jump in here, we already have a blacklist of packages to ignore, since they are known to be deprecated, or not required, or some other reason, so I guess we could have a list of other package ID's to include in the scan.

**Comment by devlead** [comment] 2019-08-26 12:43
I'm a bit worried it could cause transient and performance issues if we queried NuGet.org for meta data each time we build the site. I.e. if nuget.org result changed for any reason we could end up with an empty/random addins missing/added with no audit to why and how that happened.

The yaml files are essentially a cache of which packages to fetch, so that essentially could be an from repo external file provided by AddinDiscoverer just like the excel reports. 

Having no audit at all would also make it easy to add malicious packages to our page which should be something to consider too.

**Comment by devlead** [comment] 2019-08-29 07:52
@Jericho Haven't tried this one, but I suspect this is an Cake addin, why isn't this addin auto discovered?
https://www.nuget.org/packages/Cake.GitLabAPICI

What are the criteria?

**Comment by gep13** [comment] 2019-08-29 08:11
@devlead that addin was pushed to NuGet.org 2 days ago.  Cake.AddinDiscoverer hasn't ran in the last few days do to an error being caused by the changes made to how NuGet.org search results are returned.

This addin would be picked up automatically, as it follows the same conventions, it is just that is hasn't ran (or rather, hasn't completed the run).

**Comment by Jericho** [comment] 2019-08-29 10:39
@devlead the issue that has been causing the build to fail has been confirmed to be an issue in the new search that went live on NuGet.org a few days ago. I contacted the NuGet team and they were able to reproduce. In the mean time I will have to come up with a workaround.

**Comment by pascalberger** [comment] 2020-10-04 11:47
See also https://github.com/cake-build/website/issues/313

**Comment by pascalberger** [comment] 2020-12-13 12:51
Closing this since we move into the opposite direction: Addin discoverer responsible for detecting addins and suggesting changes to the website.

There are several advantages to this approach:
- Performance: It's not only about queyring nuget.org on every build for possible addins, but also determine compatible Cake versions, etc. We decided to rely on Addin Discoverer as main authority to maintain addin metadata (version, compatibility, etc)
- Scope: Addin discoverer does more than just crawling addins. It also generates audit reports, can create PRs to update addins, etc. Adding all this functionality to website seems to complicate sutff more than it helps to simplify it. We have some ideas to improve website further on the available data Addin Discoverer has and can provide through the YAML files (e.g. a score rating quality of addins based on best practices).
- Customization: We have several customizations done to improve user experience on the website. E.g. adding tags for addins which don't have tags set on NuGet packages, improvements on descriptions, etc. Going a fully automated process will get rid of this possibility.
- Governance: It makes sense to have an overview about new addins detected and added. This gives us a good opportunity to review them, decide if we want to add them to the website, get back to authors to ask to get cake-contrib user added, or even point out to duplicated addins. Having this fully automated would complicate governance task.

If we want to automate process further we still can start to use something like Mergify where we define rules in which cases a PR created by Addin Discoverer will be merged without human interaction.

**Closed by pascalberger** 2020-12-13 12:51 UTC
Labels: question
