### ISSUE TITLE
Blog: Code Formatting errors

### ISSUE THREAD

**Issue by Redth** [cake-build/website#330] opened 2017-03-31 18:40 UTC
It looks like there might be an issue with the code block formatter.

Specifically, on this blog post: http://cakebuild.net/blog/2016/09/debug-cake-vscode

The first code block (the launch.json file) has some errors in it that don't appear to be incorrect in the source repository.

1. `program`'s value is missing the first `$`
2. the first `args` value is missing `${workspaceRoot}`
3. `cwd` value is missing the `{workspaceRoot}`

Here's a screenshot to illustrate:

![image](https://cloud.githubusercontent.com/assets/271950/24564472/04412828-1620-11e7-9199-dfda3658096e.png)

**Comment by daveaglick** [comment] 2017-03-31 18:44
Well that's just bizarre, it's not even consistent!

**Comment by gep13** [comment] 2017-03-31 18:54
Original source code for this blog post is [here](https://github.com/cake-build/website/blob/develop/input/blog/2016-09-27-debug-cake-vscode.md)

```
{
"version": "0.2.0",
"configurations": [
{
"name": ".NET Core Launch (console)",
"type": "coreclr",
"request": "launch",
"program": "${workspaceRoot}/tools/Cake.CoreCLR/Cake.dll",
"args": [
"${workspaceRoot}/build.cake",
"--debug",
"--verbosity=diagnostic"
],
"cwd": "${workspaceRoot}",
"stopAtEntry": true,
"externalConsole": false
}
]
}
```

**Comment by daveaglick** [comment] 2017-03-31 19:01
I think this might be coming from hljs (the JavaScript syntax highlighter) - I'm seeing some strange DOM content like:
```
<span class="math" workspaceroot>
```

If I had to guess I'd say it's interpreting the `$` symbols as something special...

**Comment by daveaglick** [comment] 2017-03-31 20:27
I take it back, this is definitely coming from a Markdig extension, just not sure which one yet. Once I find it, we can easily turn it off site-wide (and I'll turn it off in the Wyam recipes as well).

**Comment by daveaglick** [comment] 2017-03-31 20:55
Looks like it's actually a combination of two extensions:
- [Mathematics](https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/MathSpecs.md) is adding the funny span with the math class
- [GenericAttributes](https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/GenericAttributesSpecs.md) is processing the `{workspaceRoot}` text

This problem could be handled in three different ways:
- Change the set of extensions we use and disable those two
- Escape the `$`, `{`, and `}` in the code block. 
- Use code fences instead of explicit HTML code blocks (which turns off processing of those extensions)

I like the third approach since it seems more Markdown-y anyway and the extensions may be handy elsewhere. PR incoming.

**Comment by mholo65** [comment] 2017-03-31 21:40
For the old site, I had to use explicit HTML, becouse there where similar issues when using code fences.. See story here https://github.com/cake-build/website/pull/142

**Comment by daveaglick** [comment] 2017-03-31 21:48
@mholo65 Welcome to the new hotness :smile:

**Comment by daveaglick** [comment] 2017-04-12 02:32
Closing this since issue is confirmed resolved with merged PR.

**Closed by daveaglick** 2017-04-12 02:32 UTC
