### ISSUE TITLE
Addin category case sensitivity issues

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#567] opened 2018-09-04 21:28 UTC
Currently addin categories seem to be case sensitive:

![grafik](https://user-images.githubusercontent.com/2190718/45058836-2e1e7400-b09a-11e8-9b6a-9627c8a56340.png)

But links for the categories are not as both are linking to `https://cakebuild.net/dsl/tfs`

**Comment by pascalberger** [comment] 2018-09-04 21:32
Where does `Tfs` come from anyway? The addin whose description is used uses [TFS](https://github.com/cake-build/website/blob/develop/addins/Cake.Tfs.AutoMerge.yml#L9).

There was once a `Tfs` in the `Cake.Tfs.Build.Variables` addin, but this was fixed with https://github.com/cake-build/website/commit/bde6217e90a80e0e26436cb04f04ec97cec7f701

**Comment by devlead** [comment] 2018-09-05 10:33
Amongst addins there only seems to be one
![image](https://user-images.githubusercontent.com/1647294/45087693-15987300-b107-11e8-98f8-80d5966db73a.png)

In API references there's 2
![image](https://user-images.githubusercontent.com/1647294/45087733-2f39ba80-b107-11e8-8343-5b343d9eeb80.png)

So I would suspect this is the issue
https://github.com/mabreuortega/Cake.Tfs/blob/b38e1eef7e23012078f03a56a1ead615bc6aa0a9/src/Cake.Tfs.AutoMerge/AutoMergeAliases.cs#L11

**Comment by daveaglick** [comment] 2018-09-05 13:59
Looks like a duplicate of #489 where [the complications are discussed in a little more detail](https://github.com/cake-build/website/issues/489#issuecomment-366696560)

**Closed** 2019-08-17 20:05 UTC
Labels: duplicate
