### ISSUE TITLE
Document NuGet.config configuration 

### ISSUE THREAD

**Issue by devlead** [cake-build/website#470] opened 2018-01-04 19:27 UTC
cake-build/cake#1932 introduced Cake configuration for the location of NuGet.config and was released in 0.24.0, this should be documented among the other default values.

**Comment by mgnslndh** [comment] 2020-10-04 17:35
I think this has already been resolved by #590 or am I missing something?

**Comment by pascalberger** [comment] 2020-10-04 18:10
@mgnslndh You're right. Thanks for catching that 👍 

Closing as duplicate of https://github.com/cake-build/website/issues/590

**Closed by pascalberger** 2020-10-04 18:10 UTC
Labels: hacktoberfest, help wanted
