### ISSUE TITLE
Add a page describing how to pass information using arguments and env

### ISSUE THREAD

**Issue by nikhilagrawaldotnet** [cake-build/website#498] opened 2018-03-06 08:05 UTC
Continuing from https://github.com/cake-build/website/pull/182, could we add a page describing how to pass multiple arguments to bootstrapper that can be passed to cake script.

Cheers :)

**Comment by gep13** [comment] 2018-03-06 08:16
@nikhilagrawaldotnet are you in a position to do a PR for this?

**Comment by nikhilagrawaldotnet** [comment] 2018-03-06 12:10
Will try.

**Comment by pascalberger** [comment] 2020-10-11 20:49
This seems like a duplicate of #383

**Closed by pascalberger** 2020-10-11 20:49 UTC
